CREATE TABLE images (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 study_record_id BIGINT UNSIGNED,
 original_filename VARCHAR(255) NOT NULL,
 media_type VARCHAR(32) NOT NULL,
 size_bytes BIGINT UNSIGNED NOT NULL,
 width INT UNSIGNED NOT NULL,
 height INT UNSIGNED NOT NULL,
 content_hash CHAR(64) NOT NULL,
 storage_path VARCHAR(255) NOT NULL,
 prompt TEXT NOT NULL,
 status VARCHAR(24) NOT NULL,
 description_json JSON,
 description_model VARCHAR(128) NOT NULL,
 description_task_id BIGINT UNSIGNED NOT NULL,
 derived_document_id BIGINT UNSIGNED,
 last_error TEXT NOT NULL,
 created_at DATETIME(6) NOT NULL,
 updated_at DATETIME(6) NOT NULL,
 INDEX idx_images_status(status),
 INDEX idx_images_record(study_record_id),
 INDEX idx_images_hash_created(content_hash,created_at),
 UNIQUE KEY uq_images_description_task(description_task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
